name: lingu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - spacy=3.7
  - jieba=0.42
  - scikit-learn=1.4
  - pandas=2.0
  - numpy=1.24
  - matplotlib=3.7
  - seaborn=0.12
  - pip
  - pip:
    - langdetect==1.0.9
    - wordcloud==1.9.3
    - pandasql==0.7.3